spring.application.name=sprint-boot-testing
spring.jpa.show-sql=true

# Give it a fixed, predictable name instead of a random UUID
#spring.datasource.url=jdbc:h2:mem:employeedb;DB_CLOSE_DELAY=-1

# Explicit credentials (rarely needed, but sometimes required by tooling)
#spring.datasource.username=sa
#spring.datasource.password=

# Enable browser console for manual inspection
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://ep-sweet-butterfly-za6mjjd8.c-2.eu-west-2.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_syZ0o8lpmDWH
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update